vscode:
  extensions:
    - ms-python.python
    - DavidAnson.vscode-markdownlint
    - EditorConfig.EditorConfig

tasks:
  - name: Setup Astro CLI
    command: |
      curl https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.0/cloud-cli_1.3.0_Linux_x86_64.tar.gz -o astrocloudcli.tar.gz
      tar xzf astrocloudcli.tar.gz && rm astrocloudcli.tar.gz
      sudo mv astrocloud /usr/local/bin/astro
      echo 'y' | astro dev init
      astro dev start

  - name: Setup Pyenv
    command: |
      pyenv virtualenv airflow_env
      pyenv activate airflow_env
      pip install -r requirements.txt
      pip install "apache-airflow==2.2.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.2/constraints-3.8.txt"

ports:
  - port: 8080
    onOpen: open-browser
    visibility: private
  - port: 5432
    onOpen: ignore
    visibility: private
